### ISSUE TITLE
Time out connection to AllegroGraph Repo

### ISSUE THREAD

**Issue by amejiarosario** [emk/rdf-agraph#4]
Every time I tried to login I got the time out error:
I can connect just fine with phifty/agraph but with gem I can't. Any Suggestion?

```
url = "http://user:password@example.org:8080/repositories/ComputerScience_test"
repo = RDF::AllegroGraph::Repository.new(url, :create => true)

Errno::ETIMEDOUT: Operation timed out - connect(2)
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:644:in `initialize'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:644:in `open'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:644:in `block in connect'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/timeout.rb:44:in `timeout'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/timeout.rb:89:in `timeout'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:644:in `connect'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:637:in `do_start'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:626:in `start'
    from /Users/adrian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/net/http.rb:490:in `start'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/transport-1.0.3/lib/transport/http.rb:22:in `perform_request'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/transport-1.0.3/lib/transport/http.rb:14:in `perform'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/transport-1.0.3/lib/transport/json.rb:25:in `perform_http_transport'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/transport-1.0.3/lib/transport/json.rb:17:in `perform'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/transport-1.0.3/lib/transport/common.rb:33:in `request'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/agraph-0.1.5/lib/allegro_graph/server.rb:43:in `request_json'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/agraph-0.1.5/lib/allegro_graph/catalog.rb:58:in `repositories'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/agraph-0.1.5/lib/allegro_graph/repository.rb:36:in `exists?'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/agraph-0.1.5/lib/allegro_graph/repository.rb:48:in `create_if_missing!'
    from /Users/adrian/.rvm/gems/ruby-1.9.2-p290/gems/rdf-agraph-0.3.1/lib/rdf/allegro_graph/repository.rb:36:in `initialize'
    from (irb):390:in `new'
```

**Comment by abrisse** [comment]
Hi @amejiarosario,

Do you still encounter the problem with the 0.4 version ?
